name: Deployment
on:
  push:
    branches:
      - master
      - dev

env:
  sit: GILBERT_SUBAY


jobs:
#  let say ini adalah Build dan deploy sit job

  test:
    environment: sit
    env:
      MONGO_CLUSTER_ADDRESS: cluster0.1iwqjzm.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "MONGO_DB_USERNAME:${{ env.MONGO_USERNAME }}"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGO_DB_USERNAME:${{ env.MONGO_USERNAME }}"
          echo: my name is: ${{  }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "..."
